language: java
dist: trusty
jdk:
#  - openjdk6
#  - oraclejdk7
  - openjdk7
  - oraclejdk8

branches:
  except:
    - appveyor

before_install:
  # output env info
  - ls -l /usr/lib/jvm
  - echo "JAVA_HOME=$JAVA_HOME"
  - echo "PATH=$PATH"
  - ./mvnw --version

after_success:
  - ./mvnw clean cobertura:cobertura coveralls:report

# cache between builds
cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/pip
